### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by deepkyu** [mindslab-ai/pnlp-mixer#3]
https://github.com/mindslab-ai/pnlp-mixer#training--testing

https://github.com/mindslab-ai/pnlp-mixer/blob/master/run.py#L142-L148

For checkpoint, it should be `-p`, not `-r`.

**Comment by tonyswoo** [comment]
Right, I think I meant to use -r (short for resume) for checkpoint designation but ended just using -p. 

My Bad.
